### ISSUE TITLE
XEP-0156 _xmppconnect is vulnerable to MITM

### ISSUE THREAD

**Issue by moparisthebest** [tigase/tigase-http-api#8]
Context: https://mail.jabber.org/pipermail/standards/2022-February/038759.html

Vulnerable code: https://github.com/tigase/tigase-http-api/blob/2346fb8d4f7adf09707554dc16976f8e87f77548/src/main/groovy/tigase/http/modules/dnswebservice/DnsResolver.java#L168

**Comment by woj-tek** [comment]
We opted to remove this code altogether in favour of host-meta servlet.
